let demoPlan = #"""
{"format_version":"0.1","terraform_version":"0.13.4","planned_values":{"root_module":{"resources":[{"address":"local_file.foo","mode":"managed","type":"local_file","name":"foo","provider_name":"registry.terraform.io/hashicorp/local","schema_version":0,"values":{"content":"foo!","content_base64":null,"directory_permission":"0777","file_permission":"0777","filename":"./foo.bar","sensitive_content":null}},{"address":"null_resource.dummy-resource","mode":"managed","type":"null_resource","name":"dummy-resource","provider_name":"registry.terraform.io/hashicorp/null","schema_version":0,"values":{"triggers":null}}]}},"resource_changes":[{"address":"local_file.foo","mode":"managed","type":"local_file","name":"foo","provider_name":"registry.terraform.io/hashicorp/local","change":{"actions":["create"],"before":null,"after":{"content":"foo!","content_base64":null,"directory_permission":"0777","file_permission":"0777","filename":"./foo.bar","sensitive_content":null},"after_unknown":{"id":true}}},{"address":"null_resource.dummy-resource","mode":"managed","type":"null_resource","name":"dummy-resource","provider_name":"registry.terraform.io/hashicorp/null","change":{"actions":["create"],"before":null,"after":{"triggers":null},"after_unknown":{"id":true}}}],"configuration":{"root_module":{"resources":[{"address":"local_file.foo","mode":"managed","type":"local_file","name":"foo","provider_config_key":"local","expressions":{"content":{"constant_value":"foo!"},"filename":{"references":["path.module"]}},"schema_version":0},{"address":"null_resource.dummy-resource","mode":"managed","type":"null_resource","name":"dummy-resource","provider_config_key":"null","schema_version":0}]}}}
"""#.data(using:.utf8)!
let emptyPlan = #"""
{"format_version":"0.1","terraform_version":"0.13.4","planned_values":{"root_module":{}},"configuration":{"root_module":{}}}
"""#.data(using:.utf8)!
let outputPlan = #"""
{"format_version":"0.1","terraform_version":"0.13.4","planned_values":{"outputs":{"anOutput":{"sensitive":false,"value":"Hello World"}},"root_module":{}},"output_changes":{"anOutput":{"actions":["create"],"before":null,"after":"Hello World","after_unknown":false}},"prior_state":{"format_version":"0.1","terraform_version":"0.13.4","values":{"outputs":{"anOutput":{"sensitive":false,"value":"Hello World"}},"root_module":{}}},"configuration":{"root_module":{"outputs":{"anOutput":{"expression":{"constant_value":"Hello World"}}}}}}
"""#.data(using:.utf8)!
let variablesPlan = #"""
{"format_version":"0.1","terraform_version":"0.13.4","variables":{"anInput":{"value":"foo"}},"planned_values":{"outputs":{"anOutput":{"sensitive":false,"value":"foo"}},"root_module":{}},"output_changes":{"anOutput":{"actions":["create"],"before":null,"after":"foo","after_unknown":false}},"prior_state":{"format_version":"0.1","terraform_version":"0.13.4","values":{"outputs":{"anOutput":{"sensitive":false,"value":"foo"}},"root_module":{}}},"configuration":{"root_module":{"outputs":{"anOutput":{"expression":{"references":["var.anInput"]}}},"variables":{"anInput":{}}}}}
"""#.data(using:.utf8)!
